AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - '**/db/schema.rb'
    - '**/*.gemspec'
    - '**/vendor/**/*'
    - '**/bin/*'
    - '**/node_modules/**/*'

Layout/LineLength:
  Description: 'Limit lines to 120 characters.'
  Max: 120

Metrics/AbcSize:
  Max: 20
  Exclude:
    - '**/db/migrate/*'

Metrics/BlockLength:
  Exclude:
    - '**/spec/**/*'
    - '**/config/routes.rb'
    - '**/config/environments/*'

Metrics/MethodLength:
  Max: 15
  Exclude:
    - '**/db/migrate/*'

Style/Documentation:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

